"""initial migration

Revision ID: 5e755d21e1bf
Revises: 
Create Date: 2023-12-11 10:30:47.356484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e755d21e1bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_item',
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('amount_in_stock', sa.Integer(), nullable=False),
    sa.Column('amount_sold', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('latest_sale', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sku'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_item')
    # ### end Alembic commands ###
