"""changed `amount_in_stock` to `quantity_available`

Revision ID: 62e44cca0dba
Revises: c5ed98a8f947
Create Date: 2023-12-16 20:55:46.723020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e44cca0dba'
down_revision = 'c5ed98a8f947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_available', sa.Integer(), nullable=True))
        batch_op.drop_column('amount_in_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_in_stock', sa.INTEGER(), nullable=True))
        batch_op.drop_column('quantity_available')

    # ### end Alembic commands ###
