"""changed OrderItem

Revision ID: 953e683e97e6
Revises: 62e44cca0dba
Create Date: 2023-12-23 03:43:00.840522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953e683e97e6'
down_revision = '62e44cca0dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
