"""refactored models to include OrderItem as a model

Revision ID: f1ec23dce0a6
Revises: 0685562af965
Create Date: 2023-12-16 03:08:22.222648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ec23dce0a6'
down_revision = '0685562af965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'item_id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.drop_column('product_amount')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.INTEGER(), nullable=True))

    op.drop_table('order_item')
    # ### end Alembic commands ###
